name: Build and Deploy – Docs

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ENV_STAGE: stage

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.prep.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - id: prep
        run: |
          TAG=${GITHUB_SHA::7}
          IMAGE="${{ env.REGISTRY }}/edenartlab/docs"
          {
            echo "tagged_image=${IMAGE}:${TAG}"
            echo "tag=${TAG}"
            echo "image=${IMAGE}"
          } >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.prep.outputs.tagged_image }}
            ${{ steps.prep.outputs.image }}:latest
